# Generated by Django 4.0.3 on 2022-04-05 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=24, null=True)),
                ('last_name', models.CharField(blank=True, max_length=24, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/profile')),
                ('fast', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salavat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prayer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quran', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
