# Generated by Django 4.0.3 on 2022-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_fast_remove_profile_prayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code_melli',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
