# Generated by Django 4.0.3 on 2022-04-04 08:18

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fast',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayer',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quran',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fast',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quran',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
