# Generated by Django 4.0.3 on 2022-04-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_prayer_type_prayer_type_fast_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fast',
            name='type',
        ),
    ]
