# Generated by Django 4.0.3 on 2022-04-04 09:51

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_fast_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='user',
            field=phone_field.models.PhoneField(blank=True, help_text='to send sms when charity done...', max_length=31),
        ),
    ]
