# Generated by Django 4.0.3 on 2022-04-06 09:02

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_prayer_user_alter_quran_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_type', models.CharField(max_length=16)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
