# Generated by Django 4.0.3 on 2022-04-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_charitylist_acceptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charitylist',
            name='acceptor',
        ),
    ]
