# Generated by Django 4.0.3 on 2022-04-08 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_remove_charitylist_acceptor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fast',
        ),
        migrations.DeleteModel(
            name='Prayer',
        ),
        migrations.DeleteModel(
            name='Quran',
        ),
        migrations.DeleteModel(
            name='Salavat',
        ),
        migrations.AddField(
            model_name='charitylist',
            name='acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charitylist',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charitylist',
            name='prayer_sub_type',
            field=models.CharField(blank=True, choices=[('نماز آیات', 'نماز آیات'), ('نماز نذر', 'نماز نذر'), ('نماز احتیاط', 'نماز احتیاط'), ('نماز میت', 'نماز میت'), ('نماز نافله', 'نماز نافله'), ('نماز جعفر طیار', 'نماز جعفر طیار'), ('نماز لیله الدفن', 'نماز لیله الدفن'), ('نماز شب', 'نماز شب')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='charitylist',
            name='user',
            field=phone_field.models.PhoneField(blank=True, help_text='to send sms when charity done...', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='charitylist',
            name='when_accept',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charitylist',
            name='charity_type',
            field=models.CharField(choices=[('نماز واجب', 'نماز واجب'), ('نماز مستحب', 'نماز مستحب'), ('یک روز کامل', 'یک روز کامل'), ('ختم', 'ختم'), ('جزء', 'جزء'), ('صلوات', 'صلوات'), ('روزه', 'روزه')], default='نماز واجب', max_length=16),
        ),
    ]
