# Generated by Django 4.0.3 on 2022-04-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_when_accept_charitylist_when_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charitylist',
            options={'verbose_name': 'Charity List', 'verbose_name_plural': 'Charity List'},
        ),
    ]
