# Generated by Django 4.0.3 on 2022-04-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_charitylist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitylist',
            name='info_for_who_mentioned',
            field=models.CharField(default='', help_text='نام و نام خانوادگی کسی که برای روح او خیرات انجام می شود.', max_length=128),
            preserve_default=False,
        ),
    ]
