# Generated by Django 4.0.3 on 2022-04-13 10:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_charitylist_info_for_who_mentioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitylist',
            name='purchase_code',
            field=models.CharField(default=main.models.random_number_5, max_length=6, unique=True),
        ),
    ]
