# Generated by Django 4.0.3 on 2022-04-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_charitylist_purchase_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charitylist',
            old_name='info_for_who_mentioned',
            new_name='mentioned_info',
        ),
    ]
