# Generated by Django 4.0.3 on 2022-04-13 10:15

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_info_for_who_mentioned_charitylist_mentioned_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitylist',
            name='user',
            field=phone_field.models.PhoneField(default='', help_text='to send sms when charity done...', max_length=31),
            preserve_default=False,
        ),
    ]
