# Generated by Django 4.0.3 on 2022-04-04 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ختم', 'ختم'), ('جزء', 'جزء')], default='جزء', max_length=12)),
                ('how_many', models.PositiveSmallIntegerField()),
                ('created_at', django_jalali.db.models.jDateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_type', models.CharField(choices=[('نماز واجب', 'نماز واجب'), ('نماز مستحب', 'نماز مستحب'), ('یک روز کامل', 'یک روز کامل')], default='یک روز کامل', max_length=24)),
                ('what_kind', models.CharField(blank=True, choices=[('نماز آیات', 'نماز آیات'), ('نماز نذر', 'نماز نذر'), ('نماز احتیاط', 'نماز احتیاط'), ('نماز میت', 'نماز میت'), ('نماز نافله', 'نماز نافله'), ('نماز جعفر طیار', 'نماز جعفر طیار'), ('نماز لیله الدفن', 'نماز لیله الدفن'), ('نماز شب', 'نماز شب')], max_length=32, null=True)),
                ('how_many', models.PositiveSmallIntegerField()),
                ('created_at', django_jalali.db.models.jDateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many', models.PositiveSmallIntegerField()),
                ('created_at', django_jalali.db.models.jDateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
